Installation
ocrearyy/Space-Travelers pull request #35
Opened 2022-05-13 21:26 UTC by AminaBuhari

Hi Reviewer 😀, 
In this task, my partner @oshanedesign and I @AminaBuhari  designed a web application from the data gotten from the SpaceX API. The application will allow users to book rockets and join selected space missions.
To highlight the task 🎯 We: - 

- Created a Kanban board and distributed the task which is available on the projects page. 

Happy review.

2022-05-13 23:06 UTC, bimbolabuari requested changes
Hi Team , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- App works as required


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-13 23:06 UTC, bimbolabuari commented on src/Components/NavigationBar.js
> +    </ul>
As required, Kindly use `<NavLink />` for the page navigation link
>![image](https://user-images.githubusercontent.com/66112760/168397421-2344b8ef-0487-4e3c-93f9-2addae080ce8.png)

2022-05-14 02:30 UTC, oshanedesign commented on src/Components/NavigationBar.js
> +    </ul>
Hi @bimbolabuari , thanks for that. Changes added . 
![e64](https://user-images.githubusercontent.com/40554384/168407588-a263321d-1169-4548-a00a-89931a0c3679.PNG)

2022-05-14 03:22 UTC, omar-labana commented
# **Approved ✔️**

Hi @AminaBuhari and @oshanedesign 

Congratulations on completing this project! 👏🏼 🎉

You have correctly implemented all of the requirements📃 correctly and without any errors⚠️ or bugs🪲.

Cheers and good luck in your next milestones! 🍀

Feel free to leave any questions or comments in the PR thread(don't forget to tag me 😄) if something is not 100% clear.

---
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-14 03:25 UTC, merged